# Generated by Django 5.2.6 on 2025-09-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["date_added"]},
        ),
    ]
