# Generated by Django 5.2.6 on 2025-09-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodie_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name": "Category"},
        ),
    ]
